name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PSW}}
      run: |
        docker login -u $DOCKER_USER 'p' $DOCKER_PSW
    - name: docker build
      run: | 
        docker image build -t hazemamamou/imageh .
    - name: docker push
      run: |
        docker push hazemamamou/imageh
