name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PSW: ${{secrets.DOCKER_PSW}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PSW
    - name: docker build
      run: | 
       echo "${{ secrets.DOCKER_PSW }}" | docker login -u "hazemamamou" --password-stdin
        docker image build -t hazemamamou/imageh .
    - name: docker push
      run: |
        docker push hazemamamou/imageh
